#!/usr/bin/env python3
"""Generate each skill's references/constraints.md from ontology + manifest.

Why generated, not hand-written: the live-run (v4 Sprint 3) found
ecom-compliance's constraints.md carrying unrelated advertising/listing rules,
and ecom-listing missing the Shopify ids its own playbook self-check cited.
Hand-maintained constraint lists drift from the manifest and from the ontology.

The single source is `ontology/constraints.yaml`; the filter is each skill's
`uses_constraints` in its manifest. A constraint appears in a skill's file iff
it is listed there — no more (no foreign-domain rules), no less (every id the
playbook references is in uses_constraints, enforced by gate S6).

Run after editing any manifest's uses_constraints. `verify_all.py --s6` checks
the output is fresh, the same way N7 checks dist/.
"""
from __future__ import annotations

import pathlib
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
CONSTRAINTS = ROOT / "ontology" / "constraints.yaml"


def load_constraints() -> dict[str, dict]:
    data = yaml.safe_load(CONSTRAINTS.read_text(encoding="utf-8")) or []
    return {c["id"]: c for c in data if isinstance(c, dict) and "id" in c}


def render(skill: str, ids: list[str], cmap: dict[str, dict]) -> str:
    lines = [
        f"# Constraints: {skill}",
        "",
        "<!-- generated by scripts/gen_skill_constraints.py — do not edit by hand -->",
        "",
        f"Filtered from `ontology/constraints.yaml` by this skill's "
        f"`uses_constraints` ({len(ids)} constraints).",
        "",
    ]
    if not ids:
        # S4 forbids placeholder shells; this is a real statement, not a stub.
        # A skill with no hard platform constraints (applicability reasons about
        # whether to use AI at all) is a fact about the domain, marked so the
        # substance gate treats it as intentional rather than unfinished.
        lines.append("<!-- intentionally-empty: this skill reasons about method "
                     "fit, not platform limits; it declares no hard constraints -->")
        lines.append("")
        lines.append("This skill carries no platform constraints. Its domain is "
                     "judgement — whether AI suits a task, what data a decision "
                     "needs — not the fixed limits (character caps, byte limits, "
                     "fee schedules) that the other skills enforce. Boundaries for "
                     "this skill live in the boundaries reference, not here.")
        return "\n".join(lines) + "\n"

    # Group by platform for readability; ontology ids are `<platform>.<path>`.
    by_platform: dict[str, list[str]] = {}
    for cid in sorted(ids):
        platform = cid.split(".", 1)[0]
        by_platform.setdefault(platform, []).append(cid)

    lines.append("Each row is a hard limit this skill's prompts must respect; the "
                 "playbook self-check verifies output against these ids, and gate "
                 "`O5` keeps the values here in step with the ontology.")
    lines.append("")
    for platform in sorted(by_platform):
        lines.append(f"## {platform}")
        lines.append("")
        lines.append("| Constraint | Value | Source |")
        lines.append("|---|---|---|")
        for cid in by_platform[platform]:
            c = cmap[cid]
            val = c.get("value", "")
            unit = c.get("unit", "")
            valcell = f"{val} {unit}".strip() if val != "" else "—"
            src = c.get("source", "")
            srccell = f"`{src}`" if src else "—"
            lines.append(f"| `{cid}` | {valcell} | {srccell} |")
        lines.append("")
    lines.append("To change any value, edit `ontology/constraints.yaml` (never this "
                 "generated file) and re-run `scripts/gen_skill_constraints.py`; the "
                 "prompts that cite these ids update through the same source.")
    return "\n".join(lines) + "\n"


def main() -> int:
    cmap = load_constraints()
    for sk in sorted(SKILLS.iterdir()):
        mf = sk / "manifest.yaml"
        if not mf.exists():
            continue
        m = yaml.safe_load(mf.read_text(encoding="utf-8"))
        ids = m.get("uses_constraints") or []
        # An id in uses_constraints that isn't in the ontology is a broken
        # reference — surface it rather than silently dropping it.
        unknown = [i for i in ids if i not in cmap]
        if unknown:
            print(f"  ! {sk.name}: uses_constraints has unknown ids: {unknown}")
        ids = [i for i in ids if i in cmap]
        out = sk / "references" / "constraints.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(render(m.get("name", sk.name), ids, cmap), encoding="utf-8")
        print(f"  {sk.name}: {len(ids)} constraints -> {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
